PosKasir/Pages/Cart/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PosKasir.Models;
using PosKasir.Service;

namespace PosKasir.Pages.Cart
{
    public class DeleteModel : PageModel
    {
        private readonly AlatTulisService _alatTulisMan;
        private readonly IDataProtector _protector;

        [BindProperty(SupportsGet = true)]
        public string ProtectedData { get; set; }

        [BindProperty(SupportsGet = true)]
        public ViewModel Form { set; get; }

        public DeleteModel(AlatTulisService alatTulisService, IDataProtectionProvider provider)
        {
            this._alatTulisMan = alatTulisService;
            _protector = provider.CreateProtector("AlatTulisProtector");
        }
        public async Task<ActionResult> OnGetAsync()
        {
            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._alatTulisMan.GetLogin(userNameLogin)).UserId;

            var timeLimit = _protector.ToTimeLimitedDataProtector();
            Form.AlatTulisId = Convert.ToInt32(timeLimit.Unprotect(ProtectedData));

            Form = await _alatTulisMan.GetPurchaseByFoodId(Form.AlatTulisId, userIdLogin);

            if (Form == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._alatTulisMan.GetLogin(userNameLogin)).UserId;

            try
            {
                var timeLimit = _protector.ToTimeLimitedDataProtector();
                Form.AlatTulisId = Convert.ToInt32(timeLimit.Unprotect(ProtectedData));
            }
            catch (Exception)
            {
                return RedirectToPage("/Cart/Index");
            }


            Form = await _alatTulisMan.GetPurchaseByFoodId(Form.AlatTulisId, userIdLogin);

            await _alatTulisMan.DeleteCart(Form.AlatTulisId, Form.UserId);
            return RedirectToPage("/Cart/Index");
        }
    }
}

PosKasir/Pages/Cart/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PosKasir.Models;
using PosKasir.Service;

namespace PosKasir.Pages.Cart
{
    [Authorize(Roles = RoleModel.UserAdmin)]
    public class IndexModel : PageModel
    {
        private readonly AlatTulisService _alatTulisMan;
        private readonly IDataProtector _protector;

        public List<CartModel> Carts { get; set; }
        public ViewModel Bill { get; set; }

        [TempData]
        public string SuccessMessage { get; set; }
        public IndexModel(AlatTulisService alatTulisService, IDataProtectionProvider provider)
        {
            this._alatTulisMan = alatTulisService;
            this._protector = provider.CreateProtector("AlatTulisProtector");
        }
        public async Task<IActionResult> OnGetAsync()
        {

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var findLogin = await this._alatTulisMan.GetLogin(userNameLogin);

            await this._alatTulisMan.FetchAllById(findLogin.UserId);
            this.Carts = this._alatTulisMan.Carts;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var findLogin = await this._alatTulisMan.GetLogin(userNameLogin);
            await this._alatTulisMan.FetchAllById(findLogin.UserId);
            this.Carts = this._alatTulisMan.Carts;

            var tanggalSekarang = DateTimeOffset.Now;

            foreach (var item in this.Carts)
            {
                Bill = new ViewModel()
                {
                    UserId = item.UserId,
                    AlatTulisId = item.AlatTulisId,
                    AlatTulisName = item.AlatTulisName,
                    Stock = item.Stock,
                    PurchaseDate = tanggalSekarang
                };

                var result = await this._alatTulisMan.InsertOrder(Bill);
                if (result == false)
                {
                    SuccessMessage = "Failed";
                    return Page();
                }

            };

            await this._alatTulisMan.SaveToDatabase();

            return Page();
        }

        public IActionResult OnPostEdit(int UnProtected)
        {
            var timeLimitProtector = _protector.ToTimeLimitedDataProtector();

            string tempUnProtected = UnProtected.ToString();
            string ProtectedData = timeLimitProtector.Protect(tempUnProtected, lifetime: TimeSpan.FromSeconds(5));

            return Redirect($"~/Cart/Update/{ProtectedData}");
        }

        public IActionResult OnPostDelete(int UnProtected)
        {
            var timeLimit = _protector.ToTimeLimitedDataProtector();

            string tempUnProtected = UnProtected.ToString();
            string ProtectedData = timeLimit.Protect(tempUnProtected, lifetime: TimeSpan.FromSeconds(5));

            return Redirect($"~/Cart/Delete/{ProtectedData}");
        }
    }
}

PosKasir/Pages/Cart/Insert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PosKasir.Models;
using PosKasir.Service;

namespace PosKasir.Pages.Cart
{
    [Authorize(Roles = RoleModel.UserAdmin)]
    public class InsertModel : PageModel
    {
        private readonly AlatTulisService _alatTulisMan;
        [BindProperty(SupportsGet = true)]
        public ViewModel Form { get; set; }

        [BindProperty(SupportsGet = true)]
        public List<AlatTulisViewModel> List { get; set; }

        [TempData]
        public string SuccessMessage { get; set; }

        [TempData]
        public int SuccessValue { get; set; }

        public string Message { get; set; }

        public InsertModel(AlatTulisService alatTulisService)
        {
            this._alatTulisMan = alatTulisService;
        }
        public async Task<IActionResult> OnGetAsync(string id)
        {
            List = await _alatTulisMan.GetAllFood();
            return Page();

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var findLogin = await this._alatTulisMan.GetLogin(userNameLogin);
            Form.UserId = findLogin.UserId;

            var checkProductExist = await _alatTulisMan.CheckCartChargeExist(Form);

            if (checkProductExist == false)
            {
                SuccessValue = 1;
                SuccessMessage = "Produk telah ada di keranjang belanja";
                return RedirectToPage();
            }

            var stock = await _alatTulisMan.CheckStock(Form);

            if (stock == false)
            {
                SuccessValue = 1;
                SuccessMessage = "Stock anda invalid, pastikan jumlah Quantity tidak kosong dan tidak melebihi jumlah stock ";
                return RedirectToPage();
            }
            else
            {
                await _alatTulisMan.InsertCart(Form);
            }
            SuccessValue = 2;
            SuccessMessage = "Berhasil memasukan barang ke keranjang";
            return Redirect("/Cart/Index");
        }
    }
}

PosKasir/Pages/Cart/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PosKasir.Models;
using PosKasir.Service;

namespace PosKasir.Pages.Cart
{
    [Authorize(Roles = RoleModel.Admin)]
    public class UpdateModel : PageModel
    {

        private readonly AlatTulisService _alatTulisMan;
        private readonly IDataProtector _protector;
        [BindProperty(SupportsGet = true)]
        public string ProtectedData { get; set; }

        [BindProperty(SupportsGet = true)]
        public ViewModel Form { set; get; }

        public string Message { get; set; }

        public UpdateModel(AlatTulisService alatTulisService, IDataProtectionProvider provider)
        {
            this._alatTulisMan = alatTulisService;
            _protector = provider.CreateProtector("AlatTulisProtector");
        }
        public async Task<IActionResult> OnGetAsync()
        {

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._alatTulisMan.GetLogin(userNameLogin)).UserId;

            var timeLimit = _protector.ToTimeLimitedDataProtector();
            Form.AlatTulisId = Convert.ToInt32(timeLimit.Unprotect(ProtectedData));

            Form = await _alatTulisMan.GetPurchaseByFoodId(Form.AlatTulisId, userIdLogin);

            if (Form == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {

            if (ModelState.IsValid == false)
            {
                return BadRequest(ModelState);
            }

            var userNameLogin = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userIdLogin = (await this._alatTulisMan.GetLogin(userNameLogin)).UserId;

            try
            {
                var timeLimit = _protector.ToTimeLimitedDataProtector();
                Form.AlatTulisId = Convert.ToInt32(timeLimit.Unprotect(ProtectedData));
            }
            catch (Exception e)
            {
                return RedirectToPage("/Cart/Index");
            }


            Form = new ViewModel()
            {
                UserId = userIdLogin,
                AlatTulisId = Form.AlatTulisId,
                Stock = Form.Stock
            };
            var stock = await _alatTulisMan.CheckStock(Form);

            if (stock == false)
            {
                Message = "Permintaan melebihi Stock, mohon kurangi jumlah pembelian (Quantity) Anda";
                return RedirectToPage();
            }
            else
            {

                await _alatTulisMan.UpdateCart(Form);
            }

            return RedirectToPage("/Cart/Index");
        }
    }
}

PosKasir/Pages/Cart/Delete.cshtml
@page "{ProtectedData}"
@model PosKasir.Pages.Cart.DeleteModel
@{
}

<h1>Delete Data Confirmation</h1>
<form method="post">
    <div>
        <h3>Apakah anda yakin untuk menghapus @Model.Form.AlatTulisName ?</h3>
    </div>
    <br />

    <input asp-for="Form.AlatTulisId" readonly hidden />
    <input asp-for="Form.UserId" readonly hidden />
    <input asp-for="Form.AlatTulisName" readonly hidden />
    <input asp-for="Form.Stock" readonly hidden />

    <button type="submit" class="btn btn-danger">Delete</button>
</form>

PosKasir/Pages/Cart/Index.cshtml
@page
@model PosKasir.Pages.Cart.IndexModel
@{
}

<h1>Cart List</h1>
<a href="~/Cart/Insert" class="btn btn-primary">Insert</a>
<br />
<table class="table table-bordered" border="1">
    <thead>
        <tr>
            <th>User ID</th>
            <th>Materi ID</th>
            <th>Materi Name</th>
            <th>Quantity</th>
            <th>Purchase Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Carts)
        {
            <tr>
                <td>@item.UserId</td>
                <td>@item.AlatTulisId</td>
                <td>@item.AlatTulisName</td>
                <td>@item.Stock</td>
                <td>@item.PurchaseDate</td>
                <td>
                    <form asp-page-handler="edit" method="post">
                        <button class="btn btn-warning">Edit</button>
                        <input type="hidden" name="UnProtected" value="@item.AlatTulisId" />
                    </form>
                    <form asp-page-handler="delete" method="post">
                        <button class="btn btn-danger">Delete</button>
                        <input type="hidden" name="UnProtected" value="@item.AlatTulisId" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <form method="post">
        <button class="btn btn-primary" type="submit">Order</button>
    </form>
</div>

PosKasir/Pages/Cart/Insert.cshtml
@page
@model PosKasir.Pages.Cart.InsertModel
@{
}

<h3>Insert Cart</h3>
<form method="POST">
    <div class=" form-group">
        Product Name: <select class="form-control" asp-for="Form.AlatTulisId">
            @foreach (var item in Model.List)
            {
                @*<option value="@item.ProductId">@item.ProductName</option>*@
                <option value="@item.AlatTulisId">@item.AlatTulisName, Stock: @item.Stock</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Form.Stock"></label>
        <input class="form-control" asp-for="Form.Stock" />
        <span asp-validation-for="Form.Stock"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-success">Add to Cart</button>
</form>
<div>
    <p>@Model.SuccessMessage</p>
</div>

PosKasir/Pages/Cart/Update.cshtml
@page "{ProtectedData}"
@model PosKasir.Pages.Cart.UpdateModel
@{
}

    <form method="post">
        <div class="form-group">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" asp-for="Form.UserId"></label>
                <div class="form-row">
                    <input readonly hidden class="form-control-plaintext" asp-for="Form.UserId" />
                    <span asp-validation-for="Form.UserId"></span>
                </div>

            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" asp-for="Form.AlatTulisId"></label>
                <div class="form-row">
                    <input readonly class="form-control-plaintext" asp-for="Form.AlatTulisId" />
                    <span asp-validation-for="Form.AlatTulisId"></span>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label" asp-for="Form.AlatTulisName"></label>
                <div class="form-row">
                    <input readonly class="form-control-plaintext" asp-for="Form.AlatTulisName" />
                    <span asp-validation-for="Form.AlatTulisName"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" asp-for="Form.Stock"></label>
                <div class="form-row">
                    <input class="form-control" asp-for="Form.Stock" />
                    <span asp-validation-for="Form.Stock" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Update Cart</button>
        </div>
    </form>